backend:
  name: git-gateway
  branch: main
  #repo: makecodework/automaxi

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads"

collections:
  posts:
    output: true
    permalink: /posts/:path/
